from django.db import models

# Create your models here.
from django.db import models



class UniqueLocationLicense(models.Model):
    abc_license_number = models.TextField(blank=True, null=True)  # Converted to TextField
    Company_Info_License_Number = models.TextField(blank=True, null=True)  # Converted to TextField
    abc_licensee = models.TextField(null=True, blank=True)
    abc_primary_name = models.TextField(null=True, blank=True)
    abc_dba_name = models.TextField(null=True, blank=True)
    abc_mail_addr_1 = models.TextField(null=True, blank=True)
    abc_mail_addr_2 = models.TextField(null=True, blank=True)
    abc_mail_city = models.TextField(null=True, blank=True)
    abc_mail_state = models.TextField(null=True, blank=True)
    abc_mail_zip = models.TextField(null=True, blank=True)
    google_phone_number = models.TextField( null=True, blank=True)
    google_website = models.TextField(null=True, blank=True)
    yelp_phone = models.TextField( blank=True, null=True)
    yelp_web_site = models.TextField(blank=True, null=True) 
    agentsInformation_entity_name =  models.TextField(blank=True, null=True)
    agentsInformation_entity_num = models.TextField(blank=True, null=True)
    agentsInformation_org_name = models.TextField(blank=True, null=True)
    filingsInformation_entity_name = models.TextField(blank=True, null=True)
    filingsInformation_entity_num = models.TextField( blank=True, null=True)
    filingsInformation_initial_filing_date = models.TextField(blank=True, null=True)
    filingsInformation_jurisdiction = models.TextField(max_length=60,blank=True, null=True)
    filingsInformation_entity_status = models.TextField( max_length=20,blank=True, null=True)
    filingsInformation_standing_sos = models.TextField( max_length=20,blank=True, null=True)
    filingsInformation_entity_type = models.TextField(blank=True, null=True)
    filingsInformation_filing_type = models.TextField(max_length=60,blank=True, null=True)
    filingsInformation_foreign_name = models.TextField( blank=True, null=True)
    filingsInformation_standing_ftb = models.TextField( blank=True, null=True)
    filingsInformation_standing_vcfcf = models.TextField(blank=True, null=True)
    filingsInformation_standing_agent = models.TextField(blank=True, null=True)
    filingsInformation_suspension_date = models.TextField(blank=True, null=True)
    filingsInformation_last_si_file_number = models.TextField(max_length=70, blank=True, null=True)
    filingsInformation_last_si_file_date = models.TextField(blank=True, null=True)
    filingsInformation_principal_address = models.TextField( blank=True, null=True)
    filingsInformation_principal_address2 = models.TextField( blank=True, null=True)
    filingsInformation_principal_city = models.TextField( blank=True, null=True)
    filingsInformation_principal_state = models.TextField( blank=True, null=True)
    filingsInformation_principal_country = models.TextField( blank=True, null=True)
    filingsInformation_principal_postal_code= models.TextField( blank=True, null=True)
    filingsInformation_mailing_address= models.TextField( blank=True, null=True)
    filingsInformation_mailing_address2= models.TextField( blank=True, null=True)
    filingsInformation_mailing_address3= models.TextField( blank=True, null=True)
    filingsInformation_mailing_city= models.TextField( blank=True, null=True)
    filingsInformation_mailing_state= models.TextField( blank=True, null=True)
    filingsInformation_mailing_country= models.TextField( blank=True, null=True)
    filingsInformation_mailing_postal_code= models.TextField( blank=True, null=True)
    filingsInformation_principal_address_in_ca= models.TextField( blank=True, null=True)
    filingsInformation_principal_address2_in_ca= models.TextField( blank=True, null=True)
    filingsInformation_principal_city_in_ca= models.TextField( blank=True, null=True)
    filingsInformation_principal_state_in_ca= models.TextField( blank=True, null=True)
    filingsInformation_principal_country_in_ca= models.TextField( blank=True, null=True)
    filingsInformation_principal_postal_code_in_ca= models.TextField( blank=True, null=True)
    filingsInformation_llc_management_structure = models.TextField( blank=True, null=True)
    filingsInformation_type_of_business = models.TextField( blank=True, null=True)
    principalsInformation_entity_name = models.TextField(blank=True, null=True)
    principalsInformation_entity_num = models.TextField(blank=True, null=True)
    def __str__(self):
        return f"Unique Location License for {self.abc_license_number}"

class LicenseeProfile(models.Model):
    abc_license_number = models.TextField(null=True, blank=True)
    Company_Info_License_Number = models.TextField(null=True, blank=True)
    abc_business_address = models.TextField(null=True, blank=True)
    abc_county = models.TextField( null=True, blank=True)
    abc_census_tract = models.TextField(blank=True, null=True)
    abc_license_type = models.TextField( null=True, blank=True)
    abc_license_type_status = models.TextField( null=True, blank=True)
    abc_status_date = models.TextField(null=True, blank=True)
    abc_term = models.TextField( null=True, blank=True)
    abc_original_issue_date = models.TextField(null=True, blank=True)
    abc_expiration_date = models.TextField(null=True, blank=True)
    abc_master = models.TextField( null=True, blank=True)
    abc_duplicate = models.BooleanField(default=False, null=True, blank=True)
    abc_fee_code = models.TextField( null=True, blank=True)
    abc_transfers = models.TextField( null=True, blank=True)
    abc_conditions = models.TextField(null=True, blank=True, default="N/A")
    abc_operating_restrictions = models.TextField(null=True, blank=True)
    abc_disciplinary_action = models.TextField(null=True, blank=True, default="No Active Disciplinary Action found")
    abc_disciplinary_history = models.TextField(null=True, blank=True, default="No Disciplinary History found.")
    abc_holds = models.TextField(null=True, blank=True, default="No Active Holds found")
    abc_escrows = models.TextField(null=True, blank=True, default="No Escrow found")
    abc_from_license_number = models.TextField( null=True, blank=True)
    abc_transferred_on = models.TextField(null=True, blank=True)
    abc_to_license_number = models.TextField( null=True, blank=True)
    abc_transferred_on2 = models.TextField(null=True, blank=True)
    abc_license_type = models.TextField(null=True, blank=True)
    abc_file_number = models.TextField(null=True, blank=True)
    abc_lic_or_app = models.TextField(null=True, blank=True)
    abc_type_status = models.TextField(null=True, blank=True)
    abc_type_orig_iss_date = models.TextField(null=True, blank=True)
    abc_expir_date = models.TextField(null=True, blank=True)
    abc_fee_codes = models.TextField(null=True, blank=True)
    abc_dup_counts = models.TextField(null=True, blank=True)
    abc_master_ind = models.TextField(null=True, blank=True)
    abc_term_in_number_of_months = models.TextField(null=True, blank=True)
    abc_geo_code = models.TextField(null=True, blank=True)
    abc_district = models.TextField(null=True, blank=True)
    abc_licensee = models.TextField(null=True, blank=True)
    abc_primary_name = models.TextField(null=True,blank=True)
    abc_prem_addr_1 = models.TextField(null=True, blank=True)
    abc_prem_addr_2 = models.TextField(null=True, blank=True)
    abc_prem_city = models.TextField(null=True, blank=True)
    abc_prem_state = models.TextField(null=True, blank=True)
    abc_prem_zip = models.TextField(null=True, blank=True)
    abc_dba_name = models.TextField(null=True, blank=True)
    abc_prem_county = models.TextField(null=True, blank=True)
    # Data Scrapp From Google API
    google_business_name = models.TextField( null=True, blank=True)
    google_business_address = models.TextField( null=True, blank=True)
    google_place_name = models.TextField( null=True, blank=True)
    google_rating = models.TextField( null=True, blank=True)
    google_phone_number = models.TextField( null=True, blank=True)
    google_website = models.TextField(null=True, blank=True)
    google_types = models.TextField( null=True, blank=True)
    google_business_status = models.TextField( null=True, blank=True)
    # Yelp Restaurant Record
    yelp_file_number = models.TextField(blank=True, null=True) 
    yelp_license_type = models.TextField(blank=True, null=True)
    yelp_primary_name = models.TextField(blank=True, null=True)
    yelp_dba_name = models.TextField(blank=True, null=True)
    yelp_prem_addr_1 = models.TextField( blank=True, null=True)
    yelp_prem_addr_2 = models.TextField( blank=True, null=True)
    yelp_prem_city = models.TextField(blank=True, null=True)
    yelp_prem_state = models.TextField(blank=True, null=True)
    yelp_prem_zip = models.TextField(blank=True, null=True)  
    yelp_link = models.TextField(blank=True, null=True)
    yelp_name = models.TextField( blank=True, null=True)
    yelp_phone = models.TextField( blank=True, null=True)
    yelp_web_site = models.TextField(blank=True, null=True) 
    yelp_rating = models.TextField( blank=True, null=True)
    # Additional Fields
    output_license_file_status = models.BooleanField(default=False)
    yelp_file_status = models.BooleanField(default=False)
    filingsInformation_entity_num = models.TextField(blank=True, null=True)
    


class AssociatedContactMapping(models.Model):
    abc_license_number = models.TextField(null=True, blank=True)
    Company_Info_License_Number = models.TextField(blank=True, null=True)
    Company_Info_Type = models.TextField(blank=True, null=True)  # Converted to TextField
    Company_Info_Name = models.TextField(blank=True, null=True)  # Converted to TextField
    Company_Info_Role = models.TextField(blank=True, null=True)  # Converted to TextField
    agentsInformation_entity_num = models.TextField(blank=True, null=True)
    agentsInformation_org_name = models.TextField(blank=True, null=True)
    agentsInformation_first_name = models.TextField(blank=True, null=True)
    agentsInformation_middle_name = models.TextField( blank=True, null=True)
    agentsInformation_last_name = models.TextField(blank=True, null=True)
    agentsInformation_physical_address1 = models.TextField(blank=True, null=True)
    agentsInformation_physical_address2 = models.TextField( blank=True, null=True)
    agentsInformation_physical_address3 = models.TextField( blank=True, null=True)
    agentsInformation_physical_city = models.TextField(blank=True, null=True)
    agentsInformation_physical_state = models.TextField(blank=True, null=True)
    agentsInformation_physical_country = models.TextField(blank=True, null=True)
    agentsInformation_physical_postal_code = models.TextField(max_length=20,blank=True, null=True)
    agentsInformation_agent_type = models.TextField(blank=True, null=True)
    filingsInformation_entity_num = models.TextField(blank=True, null=True)
    principalsInformation_entity_num = models.TextField(blank=True, null=True)
    principalsInformation_org_name = models.TextField(blank=True, null=True)
    principalsInformation_first_name = models.TextField(blank=True, null=True)
    principalsInformation_middle_name = models.TextField( blank=True, null=True)
    principalsInformation_last_name = models.TextField(blank=True, null=True)
    principalsInformation_address1 = models.TextField(blank=True, null=True)
    principalsInformation_address2 = models.TextField( blank=True, null=True)
    principalsInformation_address3 = models.TextField( blank=True, null=True)
    principalsInformation_city = models.TextField(blank=True, null=True)
    principalsInformation_state = models.TextField(blank=True, null=True)
    principalsInformation_country = models.TextField(blank=True, null=True)
    principalsInformation_postal_code = models.TextField(max_length=20,blank=True, null=True)
    principalsInformation_position_1 = models.TextField(blank=True, null=True)
    principalsInformation_position_1 = models.TextField(blank=True, null=True)
    principalsInformation_position_2 = models.TextField(blank=True, null=True)
    principalsInformation_position_3 = models.TextField(blank=True, null=True)
    principalsInformation_position_4 = models.TextField(blank=True, null=True)
    principalsInformation_position_5 = models.TextField(blank=True, null=True)
    principalsInformation_position_6 = models.TextField(blank=True, null=True)
    principalsInformation_position_7 = models.TextField(blank=True, null=True)
    filling_information_file_status = models.BooleanField(default=False)
    principal_information_file_status = models.BooleanField(default=False)
    agentsInformation_file_status = models.BooleanField(default=False)
    data_set_1_file_status = models.BooleanField(default=False)
    data_set_2_file_status = models.BooleanField(default=False)
    


    