# Generated by Django 5.1.3 on 2024-11-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.IntegerField()),
                ("type", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LicenseNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LicenseOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.IntegerField()),
                ("primary_owner", models.CharField(max_length=255)),
                ("office_of_application", models.CharField(max_length=255)),
                ("business_name", models.CharField(max_length=255)),
                ("business_address", models.CharField(max_length=255)),
                ("county", models.CharField(max_length=100)),
                ("census_tract", models.DecimalField(decimal_places=2, max_digits=10)),
                ("licensee", models.CharField(max_length=255)),
                ("license_type", models.CharField(max_length=100)),
                ("license_type_status", models.CharField(max_length=100)),
                ("status_date", models.DateField()),
                ("term", models.CharField(max_length=100)),
                ("original_issue_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("master", models.CharField(max_length=100)),
                ("duplicate", models.IntegerField(blank=True, null=True)),
                ("fee_code", models.CharField(max_length=100)),
                ("transfers", models.CharField(max_length=255)),
                ("conditions", models.TextField(blank=True, null=True)),
                ("operating_restrictions", models.TextField(blank=True, null=True)),
                ("disciplinary_action", models.TextField(blank=True, null=True)),
                ("disciplinary_history", models.TextField(blank=True, null=True)),
                ("holds", models.TextField(blank=True, null=True)),
                ("escrows", models.TextField(blank=True, null=True)),
                (
                    "from_license_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("transferred_on", models.DateField(blank=True, null=True)),
                (
                    "to_license_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("transferred_on2", models.DateField(blank=True, null=True)),
                ("business_name_alt", models.CharField(max_length=255)),
                ("business_address_alt", models.CharField(max_length=255)),
                ("place_name", models.CharField(max_length=255)),
                ("rating", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                ("website", models.URLField(blank=True, null=True)),
                ("types", models.CharField(max_length=255)),
                ("business_status", models.CharField(max_length=100)),
            ],
        ),
    ]
