# Generated by Django 5.1.3 on 2024-11-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsinformation',
            name='entity_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
