# Generated by Django 5.1.3 on 2024-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseoutput",
            name="census_tract",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
