# Generated by Django 5.1.3 on 2024-11-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_agentsinformation_entity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalsinformation',
            name='entity_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='principalsinformation',
            name='entity_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='principalsinformation',
            name='org_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
